Read(1,"(A256)") DATALN
Read(1,"(A256)") DATALN
Read(1,*) L
Read(1,*) Ventilation

Read(1,"(A256)") DATALN
Read(1,"(A256)") DATALN
Read(1,*) D

Read(1,"(A256)") DATALN
Read(1,"(A256)") DATALN
Read(1,*) S0,Manning,Friction

read(1,"(A256)") DATALN
read(1,"(A256)") DATALN
read(1,"(I6)") n
read(1,*) Cr

read(1,"(A256)") DATALN
read(1,"(A256)") DATALN
read(1,*) C_Waterhammer,C_Air

read(1,"(A256)") DATALN
read(1,"(A256)") DATALN
read(1,*) Initial_inflow_charge,flow_depth

read(1,"(A256)") DATALN
read(1,"(A256)") DATALN
read(1,*) AirPocketLength0,VentHoleRatio

read(1,"(A256)") DATALN
read(1,"(A256)") DATALN
read(1,*) Left_boundary,Right_boundary

read(1,"(A256)") DATALN
read(1,"(A256)") DATALN
read(1,*) Time_step,Time_putout